### ISSUE TITLE
Does not work with nvm

### ISSUE THREAD

**Issue by leedm777** [jaxgeller/npm-stats#4]
After installing npm-stats, whenever I try to use [nvm](https://github.com/creationix/nvm) to switch nodes, I get an error.

``` bash
$ nvm use v4.2.2
npm ERR! Usage:
npm ERR! npm config set <key> <value>
npm ERR! npm config get [<key>]
npm ERR! npm config delete <key>
npm ERR! npm config list
npm ERR! npm config edit
npm ERR! npm set <key> <value>
npm ERR! npm get [<key>]
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v4.2.2` to unset it.
```

**Comment by jaxgeller** [comment]
I don't think this is a problem with npm-stats, but rather a problem with nvm itself. Can you give me the output your `.npmrc`? Thanks

**Comment by leedm777** [comment]
This?

``` bash
$ cat ~/.npmrc 
email=leedm777@yahoo.com
sign-git-tag=true
color=true
```

**Comment by jaxgeller** [comment]
Hmm, im using `nvm` as well, having a hard time reproducing this. Are you using `ohmyzsh`? Maybe [this](https://github.com/creationix/nvm/issues/855) is the error?

**Comment by leedm777** [comment]
I'm using quite a few shell plugins, but not `ohmyzsh`. Maybe some similar combination of things.

I'll do some debugging and see if I can figure something out. I'll close until I get some useful details.
